"""API schemas."""

from .common import (
    ResponseStatus,
    BaseResponse,
    ErrorResponse,
    PaginatedResponse,
)
from .game import (
    CreateGameRequest,
    PlayerSetupRequest,
    PlaceUnitRequest,
    MoveUnitRequest,
    EquipItemRequest,
    ChampionInstanceSchema,
    PlayerStateSchema,
    GameStateSchema,
    SynergySchema,
    PlayerSynergiesResponse,
    ShopSlotSchema,
    ShopStateSchema,
)
from .combat import (
    TeamSetup,
    SimulateCombatRequest,
    UnitCombatStats,
    CombatResultSchema,
    SimulationResultSchema,
    QuickCombatRequest,
)
from .optimizer import (
    PickReasonEnum,
    PickRecommendationSchema,
    PickAdviceRequest,
    PickAdviceResponse,
    RolldownStrategyEnum,
    RolldownPlanRequest,
    RolldownPlanResponse,
    CompStyleEnum,
    CompTemplateSchema,
    CompRecommendationSchema,
    CompRecommendRequest,
    PivotReasonEnum,
    PivotOptionSchema,
    PivotAdviceRequest,
    PivotAdviceResponse,
    PositionSchema,
    PositionRecommendationSchema,
    BoardLayoutSchema,
    OptimizeBoardRequest,
    OptimizeBoardResponse,
)

__all__ = [
    # Common
    "ResponseStatus",
    "BaseResponse",
    "ErrorResponse",
    "PaginatedResponse",
    # Game
    "CreateGameRequest",
    "PlayerSetupRequest",
    "PlaceUnitRequest",
    "MoveUnitRequest",
    "EquipItemRequest",
    "ChampionInstanceSchema",
    "PlayerStateSchema",
    "GameStateSchema",
    "SynergySchema",
    "PlayerSynergiesResponse",
    "ShopSlotSchema",
    "ShopStateSchema",
    # Combat
    "TeamSetup",
    "SimulateCombatRequest",
    "UnitCombatStats",
    "CombatResultSchema",
    "SimulationResultSchema",
    "QuickCombatRequest",
    # Optimizer
    "PickReasonEnum",
    "PickRecommendationSchema",
    "PickAdviceRequest",
    "PickAdviceResponse",
    "RolldownStrategyEnum",
    "RolldownPlanRequest",
    "RolldownPlanResponse",
    "CompStyleEnum",
    "CompTemplateSchema",
    "CompRecommendationSchema",
    "CompRecommendRequest",
    "PivotReasonEnum",
    "PivotOptionSchema",
    "PivotAdviceRequest",
    "PivotAdviceResponse",
    "PositionSchema",
    "PositionRecommendationSchema",
    "BoardLayoutSchema",
    "OptimizeBoardRequest",
    "OptimizeBoardResponse",
]
